# k8s-manifests/database/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3 # <-- THIS IS THE FIX. USE THE NEW STORAGE CLASS.
