# k8s-manifests/database/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # These values are base64 encoded.
  # Use `echo -n 'your-username' | base64` and `echo -n 'your-super-secret-password' | base64` to generate your own.
  # Default values used here are: username='root', password='password'
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=