# docker-compose.yml (Production-Ready)
services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports:
      - "80:80"  # Map host port 80 to Nginx container's port 80
    networks:
      - mern_network
    # No need for REACT_APP_API_URL here, as it's baked in during the build.
    # Make sure your React code is configured to use the correct API URL for production.

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local