# k8s-manifests/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: mern-backend
spec:
  replicas: 2 # Running 2 replicas for high availability
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      serviceAccountName: ecr-access-sa
      containers:
      - name: backend
        image: 078944522849.dkr.ecr.us-east-1.amazonaws.com/backend:27
        ports:
        - containerPort: 5050
        env:
        # Get the username from the secret.
        - name: MONGO_USER # Using a temp name
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        # Get the password from the secret.
        - name: MONGO_PASSWORD # Using a temp name
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        # Construct the final, complete URL that the application will use.
        - name: DATABASE_URL
          value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb-service:27017/employees?authSource=admin"
