# k8s-manifests/backend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP # Expose internally, Ingress will manage external access